# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tf-env-states"
    key                  = "./terraform.tfstate"
    resource_group_name  = "rg-dev-corp-demo1-state-eastus"
    storage_account_name = "stodevcorpdemo1state"
    subscription_id      = "61de5036-4b92-424d-9c58-16720e561d6e"
    use_azuread_auth     = true
  }
}
