# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.6.0"
    }
  }

  required_version = ">= 1.9.0"
}

provider "azurerm" {
  features {}
  subscription_id = "61de5036-4b92-424d-9c58-16720e561d6e"
}
