name: "Terragrunt Apply"

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "dark-contoso"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "blog-az-private-frontdoor"
  CONFIG_DIRECTORY: "./infra/regions"

jobs:
  terragrunt:
    name: "Terragrunt Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: 0.68.4

      - name: Terragrunt version
        run: terragrunt --version

      - name: Terraform version
        run: terraform --version

      - name: Get Terraform binary path
        id: tf-path
        run: echo "tf_path=$(which terraform)" >> $GITHUB_OUTPUT

      - name: Terragrunt Init
        run: terragrunt init
        env:
          TERRAGRUNT_TFPATH: ${{ steps.tf-path.outputs.tf_path }}
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Terragrunt Plan
        run: terragrunt plan -no-color
        env:
          TERRAGRUNT_TFPATH: ${{ steps.tf-path.outputs.tf_path }}
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        run: terragrunt apply -auto-approve
        env:
          TERRAGRUNT_TFPATH: ${{ steps.tf-path.outputs.tf_path }}
        working-directory: ${{ env.CONFIG_DIRECTORY }}
