name: Terragrunt Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "dark-contoso"
  TF_WORKSPACE: "blog-az-private-frontdoor"
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TERRAGRUNT_VERSION: "0.68.4"
  CONFIG_DIRECTORY: "./infra/regions"

jobs:
  terragrunt-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.8"

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt Init
        run: |
          cd ${{ env.CONFIG_DIRECTORY }}
          terragrunt run-all init --terragrunt-non-interactive

      - name: Terragrunt Plan
        run: |
          cd ${{ env.CONFIG_DIRECTORY }}
          terragrunt run-all plan --terragrunt-non-interactive

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd ${{ env.CONFIG_DIRECTORY }}
          terragrunt run-all apply --auto-approve --terragrunt-non-interactive
